version: '3.8'

services:
  db:
    image: mariadb:11.2
    container_name: mariadb
    restart: always
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      # PMA_PASSWORD: 1234
      # PMA_USER: root
      # PMA_HOSTS: db